/** Display size (px) of each background drawing – also its SVG viewBox (see DoodleSprite). */
export const DOODLE_SIZES: Record<string, [number, number]> = {
  ship: [50, 30],
  sailboat: [36, 36],
  whale: [54, 34],
  dolphin: [46, 30],
  camel: [110, 36],
  giraffe: [34, 46],
  elephant: [46, 34],
  kangaroo: [38, 38],
  bear: [46, 30],
  polarbear: [46, 30],
  panda: [38, 30],
  palm: [36, 42],
  seal: [42, 27],
  penguin: [22, 32],
  cactus: [30, 38],
  llama: [32, 38],
  windmill: [32, 44],
  reindeer: [40, 38],
  iceberg: [46, 36],
};

/** How each drawing moves while it is visible. */
export const DOODLE_MOTION: Record<string, 'sail' | 'swim' | 'jump' | 'walk' | 'hop' | 'sway' | 'bob' | 'waddle' | 'spin' | 'idle'> = {
  ship: 'sail',
  sailboat: 'sail',
  whale: 'swim',
  dolphin: 'jump',
  camel: 'walk',
  giraffe: 'walk',
  elephant: 'walk',
  kangaroo: 'hop',
  bear: 'walk',
  polarbear: 'walk',
  panda: 'idle',
  palm: 'sway',
  seal: 'bob',
  penguin: 'waddle',
  cactus: 'sway',
  llama: 'walk',
  windmill: 'spin',
  reindeer: 'walk',
  iceberg: 'bob',
};
